//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public int FUN_CODIGO { get; set; }
        public string FUN_NOME { get; set; }
        public string FUN_CPF { get; set; }
        public string FUN_RG { get; set; }
        public string FUN_ENDERECO { get; set; }
        public string FUN_BAIRRO { get; set; }
        public string FUN_CIDADE { get; set; }
        public string FUN_ESTADO { get; set; }
        public string FUN_CEP { get; set; }
        public string FUN_CELULAR_TELEFONE { get; set; }
        public string FUN_BANCO { get; set; }
        public string FUN_AGENCIA { get; set; }
        public string FUN_PIS { get; set; }
        public string FUN_ESTADO_CIVIL { get; set; }
        public int FUN_QTD_FILHOS { get; set; }
        public System.DateTime FUN_ADMISSAO { get; set; }
        public System.DateTime FUN_HORARIO { get; set; }
        public string FUN_CARGO { get; set; }
        public float FUN_SALARIO { get; set; }
        public string FUN_SITUACAO { get; set; }
    }
}
