//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEIS
    {
        public int HT_CODIGO { get; set; }
        public string HT_NOME { get; set; }
        public string HT_CNPJ { get; set; }
        public string HT_ENDERECO { get; set; }
        public string HT_CIDADE { get; set; }
        public string HT_ESTADO { get; set; }
        public string HT_TELEFONE { get; set; }
    }
}
