//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int LOG_COD { get; set; }
        public string LOG_USERNAME { get; set; }
        public string LOG_USER { get; set; }
        public string LOG_SENHA { get; set; }
        public string LOG_NIVEL { get; set; }
        public string LOG_STATUS { get; set; }
    }
}
