//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        public int PRO_CODIGO { get; set; }
        public string PRO_TIPO { get; set; }
        public string PRO_DESCRICAO { get; set; }
        public System.DateTime PRO_DATA_CADASTRO { get; set; }
        public string PRO_FORNECEDOR { get; set; }
        public string PRO_FABRICANTE { get; set; }
        public int PRO_QTD_ESTOQUE { get; set; }
        public string PRO_UNIDADE { get; set; }
        public double PRO_PRECO_CUSTO { get; set; }
        public double PRO_PRECO_VENDA { get; set; }
        public string PRO_COD_BARRAS { get; set; }
        public System.DateTime PRO_DATA_FABRICACAO { get; set; }
        public System.DateTime PRO_DATA_VALIDADE { get; set; }
    }
}
