//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUARTOS
    {
        public int QT_NUMERO { get; set; }
        public string QT_ANDAR { get; set; }
        public float QT_VALOR { get; set; }
        public string QT_TIPO { get; set; }
        public string QT_DESC { get; set; }
    }
}
