//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTORIA
    {
        public int VIS_CODIGO { get; set; }
        public string VIS_OBSERVACAO { get; set; }
        public string VIS_FUNCIONARIO { get; set; }
        public Nullable<System.DateTime> VIS_DATA_INICIAL { get; set; }
        public Nullable<int> VIS_CODIGO_PRODUTO { get; set; }
        public string VIS_DESCRICAO { get; set; }
        public Nullable<int> VIS_CODIGO_QUARTO { get; set; }
    }
}
